#!/bin/sh
set -e

echo "Running unit tests..."
npm run test:unit
echo "✅ Unit tests passed."

echo "Running integration tests..."
npm run test:integration
echo "✅ Integration tests passed."

echo "Building project..."
npm run build --workspace=apps/client
npm run build --workspace=apps/server
echo "✅ Build passed."