name: Security Pipeline

on:
  workflow_call:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  dependency-scan:
    name: Dependency Scan (SCA)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH

#   # =========================
#   # Dependency Scanning (SCA)
#   # =========================
#   dependency-scan:
#     name: Dependency Scan
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v5

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version-file: '.nvmrc'
#           cache: 'npm'
#           cache-dependency-path: package-lock.json

#       - name: Install dependencies (workspace root)
#         run: npm ci

#       - name: Run npm audit
#         run: npm audit --audit-level=high

  # =========================
  # SAST (Static Analysis)
  # =========================
  sast:
    name: SAST - CodeQL
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript

      # - name: Autobuild
      #   uses: github/codeql-action/autobuild@v4

      - name: Install dependencies
        run: npm ci
  
      - name: Analyze
        uses: github/codeql-action/analyze@v4

  # =========================
  # Secret Scanning
  # =========================
  secrets:
    name: Secret Detection
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GIT_LEAKS }}

#   # =========================
#   # Infrastructure as Code Security
#   # =========================
#   iac-security:
#     name: IaC Security Scan
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v5

#       - name: Run Semgrep IaC rules
#         uses: returntocorp/semgrep-action@v1
#         with:
#           config: p/terraform

#   # =========================
#   # SBOM generation (recommended)
#   # =========================
#   sbom:
#     name: Generate SBOM
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v5

#       - name: Generate SBOM
#         uses: anchore/sbom-action@v0